version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    ports:
      - 5050:80

# How use it ------------------------------------------
# Access PgAdmin at broswer at locahost:5050
# LOGGIN ----------------------------------------------
#      - login: PGADMIN_DEFAULT_EMAIL
#      - password: PGADMIN_DEFAULT_PASSWORD
# 
# REGISTER SERVICE STEP -------------------------------
# - GENERAL    - Name: choose a name
# -----------------------------------------------------
# - CONNECTION - Host: postgres
#              - Port: 5432
#              - Maintance database: POSTGRES_DB
#              - Username: POSTGRES_USER
#              - Password: POSTGRES_PASSWORD
#------------------------------------------------------